highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 4000
safe: true
# url: http://devendra.co/
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ""
title: Vince DeVendra's Resume
name: Vince DeVendra
email: vincedevendra@gmail.com
email_full: mailto:vincedevendra@gmail.com
github: vincedevendra
twitter: vincedevendra
medium: vincedevendra
tel: +1 617 658 3036
tel_full: tel:+16176583036
google_maps: 'https://www.google.com/maps/place/Boston,+MA/@42.3135421,-71.1972437,11z/data=!3m1!4b1!4m2!3m1!1s0x89e3652d0d3d311b:0x787cbf240162e8a0'
address:
city: Boston, MA
state:
zip-code:
country:
google_analytics: UA-69300817-1
